import { defineConfig } from "rolldown";
import { builtinModules } from "node:module";

const banner =
	"/*\n" +
	"THIS IS A GENERATED/BUNDLED FILE BY ROLLDOWN\n" +
	"if you want to view the source, please visit the github repository of this plugin\n" +
	"*/\n";

const codemirrorExternals = [
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
];

const nodeBuiltinExternals = [
	...builtinModules,
	...builtinModules.map((moduleName) => `node:${moduleName}`),
];

const production = process.env.NODE_ENV === "production";

export default defineConfig({
	input: "src/main.ts",
	external: ["obsidian", "electron", ...codemirrorExternals, ...nodeBuiltinExternals],
	output: {
		file: "main.js",
		format: "cjs",
		banner,
		minify: production,
		sourcemap: production ? false : "inline",
	},
});
